spring.datasource.url=jdbc:mysql://localhost:3306/portfolio_db
spring.datasource.username=root
spring.datasource.password=2811

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8080
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

jwt.secret=MySecretKeyForPortfolioProject2026MySecretKeyForPortfolioProject2026
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=farhaan.attar313@gmail.com
spring.mail.password=pxui uvgy vkae vlgr

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
